import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Sparkles } from 'lucide-react';
import { Reveal } from '@/components/reveal';
import { categories } from '@/lib/data';

export default function Home() { return <>
  <section className="hero"><Image className="hero-image" src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=2200&q=85" alt="Warmly lit objects arranged on a wooden table" fill priority sizes="100vw" /><div className="shell hero-content"><Reveal><p className="eyebrow">A gift shop for the in-between moments</p><h1 className="display display-xl">The right thing,<br />for <em>their</em> kind of day.</h1><p className="hero-copy">Find something that feels less like an object and more like a small, exact understanding.</p><div className="hero-actions"><Link href="/gift-finder" className="button button-primary">Find the perfect gift <ArrowUpRight size={17} /></Link><Link href="/collections" className="button button-ghost">Explore collections</Link></div></Reveal></div><div className="hero-note">Thoughtful objects, chosen with a little more attention.</div></section>
  <Reveal><section className="section"><div className="shell split-story"><div className="story-mark"><span>W</span></div><div className="story-text"><p className="eyebrow">The WRAPT point of view</p><h2 className="display display-lg">Good gifts carry a little of the giver.</h2><p>We look for the hand-warmed ceramic, the book with a generous margin, the thing that makes someone say, “How did you know?”</p><Link href="/our-story" className="text-link">Read our story <ArrowUpRight size={15} /></Link></div></div></section></Reveal>
  <section className="section" style={{ paddingTop: 35 }}><div className="shell"><Reveal><div className="finder-teaser"><div className="finder-teaser-copy"><p className="eyebrow"><Sparkles size={14} style={{ verticalAlign: 'middle', marginRight: 7 }} /> The Gift Finder</p><h2 className="display display-lg">Tell us a little.<br /><em>We’ll read between.</em></h2><p>A few questions about them, the occasion, and the feeling you want to leave behind. Then, one considered direction to start from.</p><Link href="/gift-finder" className="button button-primary">Start finding <ArrowUpRight size={17} /></Link></div></div></Reveal></div></section>
  <section className="section"><div className="shell"><Reveal><div className="section-top"><div><p className="eyebrow">The edit</p><h2 className="display display-lg section-title">A few places<br />to begin.</h2></div><Link href="/collections" className="text-link">See all ten collections <ArrowUpRight size={15} /></Link></div></Reveal><div className="collections-grid">{categories.slice(0, 6).map((category, i) => <Reveal key={category.slug} delay={i * .05}><Link href={`/collections/${category.slug}`} className="collection-card"><img className="card-image" src={category.image} alt="" /><div className="card-body"><h3>{category.name}</h3><p>{category.mood}</p></div></Link></Reveal>)}</div></div></section>
  <div className="trust-strip"><div className="shell trust-items"><span className="trust-item">Every gift, matched — not guessed.</span><span className="trust-item">Ten ways to say I was thinking of you.</span><span className="trust-item">Made for the moment.</span></div></div>
</>; }