'use client';

import { AnimatePresence, motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, RotateCcw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { categoryBySlug, finderStockImage } from '@/lib/data';

const steps = [
  { key: 'who', eyebrow: "Let's start with them", title: "Let's find something they'll actually love.", options: ['Partner', 'Parent', 'Best Friend', 'Sibling', 'Close Friend', 'Colleague', 'Child', 'Someone Special'], placeholder: 'Or tell us about them in your own words' },
  { key: 'occasion', eyebrow: 'The moment', title: "Every gift tells a story. What's this one for?", options: ['Birthday', 'Anniversary', 'Just Because', 'Congratulations', 'Thank You', 'Holiday Season', 'New Beginnings'], placeholder: 'Or describe the occasion in your own words' },
  { key: 'vibe', eyebrow: 'The feeling', title: 'Personality says more than any wish list.', options: ['Cozy & Homebody', 'Adventurous', 'Elegant & Refined', 'Playful & Fun', 'Foodie', 'Creative & Artsy', 'Bookish', 'Sentimental', 'Tech-Savvy'], placeholder: 'Add another detail about their vibe' },
  { key: 'budget', eyebrow: 'A comfortable place to start', title: 'What feels right to spend?', options: ['Under $25', '$25–$50', '$50–$100', '$100+', 'No limit'], placeholder: '' },
  { key: 'detail', eyebrow: 'One last little clue', title: 'Anything on their mind lately?', options: [], placeholder: 'A hobby, a dream, an inside joke — anything helps us get it right.' }
] as const;

type Answers = Record<string, string | string[]>;
export function GiftFinder() { const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Answers>({ vibe: [] }); const [reviewing, setReviewing] = useState(false); const [loading, setLoading] = useState(false); const [result, setResult] = useState<{ category: string; reason: string; image: string } | null>(null); const [loadingCopy, setLoadingCopy] = useState(0);
  useEffect(() => { if (!loading) return; const timer = setInterval(() => setLoadingCopy((current) => (current + 1) % 3), 1500); return () => clearInterval(timer); }, [loading]);
  const current = steps[step]; const selected = answers[current.key] ?? (current.key === 'vibe' ? [] : '');
  const choose = (option: string) => { if (current.key === 'vibe') { const vibe = Array.isArray(selected) ? selected : []; if (vibe.includes(option)) setAnswers({ ...answers, vibe: vibe.filter((item) => item !== option) }); else if (vibe.length < 3) setAnswers({ ...answers, vibe: [...vibe, option] }); } else setAnswers({ ...answers, [current.key]: option }); };
  const updateText = (value: string) => setAnswers({ ...answers, [current.key === 'vibe' ? 'vibeNote' : current.key]: value });
  const finish = async () => { setLoading(true); try { const response = await fetch('/api/gift-finder', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(answers) }); const data = await response.json(); setTimeout(() => { setResult(data); setLoading(false); }, 2500); } catch { setTimeout(() => { setResult({ category: 'cozy-comfort', reason: 'Some gifts do not need an algorithm — this one just feels right.', image: finderStockImage('cozy-comfort') }); setLoading(false); }, 2500); } };
  const next = () => { if (step === steps.length - 1) setReviewing(true); else setStep(step + 1); }; const reset = () => { setStep(0); setAnswers({ vibe: [] }); setReviewing(false); setResult(null); setLoading(false); };
  if (loading) return <div className="finder-panel loading-state"><div><div className="gift-line"><span>W</span></div><p>{['Reading between the lines...', 'Matching moments to meaning...', 'Great gifts take a little thought — almost there.'][loadingCopy]}</p></div></div>;
  if (result) { const category = categoryBySlug(result.category) ?? categoryBySlug('cozy-comfort')!; return <motion.div className="finder-panel" initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }}><p className="eyebrow">A considered direction</p><h2>We found it.</h2><h3 className="display" style={{ fontSize: 32, margin: '22px 0 5px' }}>{category.name}</h3><p style={{ color: 'var(--ink-soft)' }}>{category.mood}</p><motion.img className="result-image" src={result.image} alt="A private WRAPT gift match" initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .15, duration: .7 }} /><p className="result-reason">“{result.reason}”</p><div className="result-actions"><Link href={`/collections/${category.slug}`} className="button button-primary">Explore this collection <ArrowRight size={16} /></Link><button onClick={reset} className="button button-ghost"><RotateCcw size={15} /> Try another match</button></div></motion.div>; }
  if (reviewing) return <div className="finder-panel"><div className="progress" aria-label="Review your choices">{steps.map((item) => <span className="active" key={item.key} />)}</div><AnimatePresence mode="wait"><motion.div key="review" initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .3 }}><p className="eyebrow">One last look</p><h2>Here is what we heard.</h2><p style={{ color: 'var(--ink-soft)' }}>Everything looks right? We’ll use these details to find a thoughtful direction.</p><div className="review-list">{steps.map((item) => { const value = item.key === 'vibe' ? [...(Array.isArray(answers.vibe) ? answers.vibe : []), typeof answers.vibeNote === 'string' ? answers.vibeNote : ''].filter(Boolean).join(', ') : String(answers[item.key] || 'Not specified'); return <div className="review-row" key={item.key}><span className="eyebrow">{item.eyebrow}</span><strong>{value}</strong></div>; })}</div><div className="finder-actions"><button className="skip" onClick={() => setReviewing(false)}><ArrowLeft size={14} style={{ verticalAlign: 'middle' }} /> Back to edit</button><button className="button button-primary" onClick={finish}>Find my match <ArrowRight size={16} /></button></div></motion.div></AnimatePresence></div>;
  return <div className="finder-panel"><div className="progress" aria-label={`Step ${step + 1} of ${steps.length}`}>{steps.map((item, index) => <span className={index <= step ? 'active' : ''} key={item.key} />)}</div><AnimatePresence mode="wait"><motion.div key={current.key} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -18 }} transition={{ duration: .3 }}><p className="eyebrow">{current.eyebrow}</p><h2>{current.title}</h2>{current.options.length > 0 && <div className="chip-grid">{current.options.map((option) => <button key={option} className={`chip ${(Array.isArray(selected) ? selected.includes(option) : selected === option) ? 'selected' : ''}`} onClick={() => choose(option)}>{option}</button>)}</div>}{current.key === 'vibe' && <div className="finder-selection" aria-live="polite"><span>Selected</span>{Array.isArray(selected) && selected.length > 0 ? selected.join(', ') : 'Nothing yet'}</div>}<label htmlFor={`finder-${current.key}`} className="sr-only">{current.placeholder}</label><input id={`finder-${current.key}`} className="finder-input" placeholder={current.placeholder} value={current.key === 'vibe' ? String(answers.vibeNote || '') : Array.isArray(selected) ? '' : selected} onChange={(event) => updateText(event.target.value)} />{current.key === 'vibe' && <small style={{ color: 'var(--ink-soft)' }}>Add another detail if you like · Choose up to three.</small>}<div className="finder-actions">{step > 0 ? <button className="skip" onClick={() => setStep(step - 1)}><ArrowLeft size={14} style={{ verticalAlign: 'middle' }} /> Back</button> : <span />}{current.key === 'detail' && <button className="skip" onClick={() => setReviewing(true)}>Skip this</button>}<button className="button button-primary" onClick={next}>{step === steps.length - 1 ? 'Review my choices' : 'Continue'} <ArrowRight size={16} /></button></div></motion.div></AnimatePresence></div>;
}